baseURL = "/"
languageCode = "en-us"
title = "Aurelia"
theme = "aurelia-theme"

[params]
  pathPrefix = ""

[outputs]
  home = ["HTML", "RSS", "JSON"] 

[build]
  writeStats = true
  
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  
  [[module.mounts]]
    source = "static"
    target = "static" 