baseURL = "/"
languageCode = "en-us"
title = "Aurelia"
theme = "aurelia-theme"

[[redirects]]
  from = "/docs"
  to = "https://aurelia-1.gitbook.io/v1-docs"
  status = 301
  force = true

[taxonomies]
  authors = "authors"
  tags = "tags"
  categories = "categories"
  showcase_categories = "showcase_categories"

[permalinks]
  showcase_categories = "/showcase/category/:slug"

[params]
  pathPrefix = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.extensions]
      linkify = true
  [markup.highlight]
    style = "monokai"

[services]
  [services.disqus]
    shortname = 'aurelia-2'

[outputs]
  home = ["HTML", "RSS", "JSON"] 