baseURL = "/"
languageCode = "en-us"
title = "Aurelia"
theme = "aurelia-theme"

[params]
  pathPrefix = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "emacs"

[outputs]
  home = ["HTML", "RSS", "JSON"] 