baseURL = "/"
languageCode = "en-us"
title = "Aurelia"
theme = "aurelia-theme"

[taxonomies]
  authors = "authors"
  tags = "tags"
  categories = "categories"

[params]
  pathPrefix = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.extensions]
      linkify = true
  [markup.highlight]
    style = "monokai"

[services]
  [services.disqus]
    shortname = 'aurelia-2'

[outputs]
  home = ["HTML", "RSS", "JSON"] 

# Global pagination setting
paginate = 10