baseURL = '/'
languageCode = 'en-US'
title = 'Aurelia'

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 1

[[menus.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Learn"
  url = "/learn/"
  weight = 3

[permalinks]
  blog = "/blog/:year/:date.2006-01/:day/:slug/"

[params]
  paginate = 7