name = 'Aurelia'
license = 'MIT'
description = 'Aurelia is a theme built with Tailwind CSS and PostCSS for the Aurelia website.'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/aurelia/website'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Dwayne Charrington'
  homepage = 'https://ilikekillnerds.com'
